-- Create News Table for Spiritual News Automation
CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    url TEXT NOT NULL,
    tag TEXT DEFAULT '最新動態',
    published_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access" ON public.news
    FOR SELECT USING (true);

-- Allow authenticated (admin) write access
-- Note: Assuming admin is using service role or handled via policy later
-- For now, allowing all for initial testing if needed, but in production this should be restricted.
CREATE POLICY "Allow admin all access" ON public.news
    FOR ALL USING (true);

-- Initial Mock Data Based on 2025 Trends
INSERT INTO public.news (title, summary, url, tag, published_at)
VALUES 
(
    '「心經濟」時代：全球療癒市場規模將達 5 兆美元', 
    '隨著全球壓力指數上升，人們在心理健康與靈性成長上的投資逐年遞增。療癒經濟不再是小眾市場，而是現代人生活的核心需求。研究指出，2025 年將是「心能量」全面爆發的一年。', 
    'https://www.gvm.com.tw/article/111812', 
    '2025 趨勢', 
    '2025-02-23T00:00:00Z'
),
(
    '精準養生趨勢：AI 與頻率檢測的深度結合', 
    '擺脫「一體適用」的健康方案，透過個人化數據（如氣場頻率、DNA 檢測）量身打造修復藍圖。2025 年的科技將成為靈性修煉的最佳輔助工具，讓身心平衡更加科學與高效。', 
    'https://www.luckyphoenixmed.com/blog/2025-wellness-trends', 
    '靈性科技', 
    '2025-02-22T00:00:00Z'
),
(
    '數位排毒興起：回到「類比式」的身心連結', 
    '面對線上世界的過度刺激，越來越多人轉向「類比健康」。透過沉浸式自然工作坊與冥想，找回被科技碎片化的注意力。這是 2025 年不可忽略的心靈修復運動。', 
    'https://globalwellnesssummit.com/2025-trends/', 
    '身心平衡', 
    '2025-02-20T00:00:00Z'
);
